// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoaadbbvvbalznbrxuku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYWFkYmJ2dmJhbHpuYnJ4dWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDg1MzcsImV4cCI6MjA2NTk4NDUzN30.zLnplHypGnSE5s4qUubSWT6BFhUJ5TC8VDVIEvHkowk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);